site_name: PyBotNet
site_description: PyBotNet framework, high level remote control 

theme:
  name: 'material'
  palette:
    - scheme: default
      primary: 'Purple'
      accent: 'Purple'
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
    - scheme: slate
      primary: 'Purple'
      accent: 'Purple'
      toggle:
          icon: material/weather-night
          name: Switch to light mode

  favicon: 'favicon.png'
  features:
    - content.code.annotate 
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.annotate

repo_name: trhacknon/pybotnet
repo_url: https://github.com/trhacknon/pybotnet

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - tables
  - def_list

plugins:
  - search

nav:
  - About : index.md
  - Tutorial:
    - User Guide:
      - tutorial_user_guide/simple_usage.md
      - tutorial_user_guide/add_custom_script.md
      - tutorial_user_guide/run_in_background.md
      - tutorial_user_guide/running_pybotnet_without_coding.md
      - tutorial_user_guide/external_scripts.md
      - tutorial_user_guide/config_BotNet_class.md

    - Advanced User Guide:
      - tutorial_advanced_guide/create_custom_engine.md
      - tutorial_advanced_guide/linux_crontab.md
      - tutorial_advanced_guide/linux_services.md
      - tutorial_advanced_guide/windows_startup.md
   
  - help_pybotnet_and_get_help.md
  - development_and_contributing.md
  - release_notes.md

